name: JMeter Load Test

on:
  push:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt update
          sudo apt install jmeter -y

      - name: Run JMeter Test
        run: |
          jmeter -n -t testplanexam.jmx -l results.jtl

      - name: Generate HTML Report
        run: |
          rm -rf report
          jmeter -g results.jtl -o report
          ls -R

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report
