name: JMeter Load Test

on:
  push:
    branches: [ main ]

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Java
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk -y

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter

      - name: Run JMeter Test
        run: |
          /opt/jmeter/bin/jmeter -n -t testplanexam.jmx -l results.jtl

      - name: Generate HTML Report
        run: |
          /opt/jmeter/bin/jmeter -g results.jtl -o report

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-report
          path: report
